### PR TITLE
Fix: light-mode relay for all light protocols

### LINKED ISSUE #498: Issue: `WakuFilter` requires `WakuRelay`
## Background
Currently the `WakuFilter` protocol requires `WakuRelay` to be mounted on a light node. This is because `WakuFilter` itself is not a PubSub protocol but in its current form requires PubSub functionality on at least three counts:
1. **In order to subscribe topic handlers:** this is necessary for `WakuFilter` to be notified of new messages. Currently topic handlers can only be registered via the `WakuRelay` protocol.
2. **In order to publish:** even if the above were not true, a node with only `WakuFilter` mounted would not be able to publish messages without having a PubSub-compatible protocol mounted. `WakuRelay` is currently the only such protocol implemented, though a [`LIGHTPUSH` protocol](https://github.com/vacp2p/rfc/issues/354) is under discussion.
3. **In order to dial the full node:** the full node, where `WakuRelay` is mounted by definition, will [attempt to subscribe](https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/pubsub.nim#L374-L379) the light node as a pubsub peer when dialed and negotiate a PubSub connection. However, if `WakuRelay` is not mounted on the light node the connection attempt will fail. This currently prohibits light nodes without `WakuRelay` mounted from dialing full nodes at all, including to subscribe to a content filter.

## Why do we not want to mount `WakuRelay` on a light node?
Once a light node with `WakuRelay` mounted has opened a connection to a full node (say, to subscribe a content filter), it will be considered a "normal" PubSub peer in the full node, undergo grafting and pruning and generally behave like a full node.

### PR DESCRIPTION
**Pull request by jm-clius**
This PR closes #498. It follows the same approach as https://github.com/status-im/nim-waku/pull/518, but fixes the issue in a more general way to apply to any `light` protocol.

(Also sneaked in an unrelated CHANGELOG.md entry, which I forgot about earlier 😄.)

## Background recap

Currently `nim-libp2p` requires the same `PubSub` protocol used in full nodes (in our case, `RELAY`) to be mounted on light nodes for protocol negotiation to succeed. Detailed explanation [here](https://github.com/status-im/nim-waku/issues/498#issuecomment-828543874).
However, once a light node with `RELAY` mounted has connected to a full node (say, to `subscribe` a content filter or to perform a `lightpush`), it will be considered a "normal" PubSub peer in the full node, undergo grafting and pruning and generally behave like a full node.
This fix allows a light node to behave like a "true" light node by mounting a "light" mode of `RELAY` allowing light protocol negotation but no full-message peerings. `RELAY` is only mounted on the switch and never started. `node.wakuRelay` remains `nil` and the light node does not subscribe to any PubSub topics.

### CODE REVIEW

**Review by staheri14 — APPROVED** [review]

File: tests/v2/test_wakunode.nim [hunk 1]
```diff
@@ -210,6 +210,54 @@ procSuite "WakuNode":
 
     await node1.stop()
     await node2.stop()
+  
+  asyncTest "Filter protocol works between light node and full node":
```
Comment (oskarth) [inline tests/v2/test_wakunode.nim:214]: I'd be careful with using words such as "light" and "full", I know we often take this shortcut but being more precise here would be useful. I.e. we are really talking about adaptive nodes, that have a varying set of capabilities.

Maybe we can specify what we mean by light and full here?

Also see https://github.com/vacp2p/rfc/issues/87 for some previousy discussion

File: waku/v2/node/wakunode2.nim [hunk 2]
```diff
@@ -359,6 +359,20 @@ proc info*(node: WakuNode): WakuInfo =
   let wakuInfo = WakuInfo(listenStr: listenStr)
   return wakuInfo
 
+proc mountLightRelay*(node: WakuNode) =
```
Comment (oskarth) [inline waku/v2/node/wakunode2.nim:362]: Instead of using "light", what about something like SkeletonRelay? EmptyRelay? NonRelayingRelay? :D

Intuition: with topic sharding a node can subscribe to anything from 0 to 10 topics (say), what exactly is a light node in such a scenario? Add to that that some nodes might do storing, for a certain period of time, for some topics...etc. Desktop node is a good way to think about it, which would be neither "minimally light" nor "maximally full".

Comment (oskarth) [inline waku/v2/node/wakunode2.nim:362]: Actually, can this just be mountRelay? Then have as an argument if we want to subscribe to default topic or not. Might be cleaner? So you have

mountRelay(sub=false)
mountRelay(sub=default)
mountRelay(sub=shard1, shard2, shard3...)
etc

**Review by oskarth — COMMENTED** [review]
Some comments on getting naming and concepts right

File: tests/v2/test_wakunode.nim (hunk 1 above)
Comment (jm-clius) [reply tests/v2/test_wakunode.nim:214]: Ah, thanks, that discussion is very enlightening. Conceptually much cleaner to think in terms of capabilities.

File: waku/v2/node/wakunode2.nim (hunk 2 above)
Comment (jm-clius) [reply waku/v2/node/wakunode2.nim:362]: Yes, this makes sense. One extra layer of complexity here is that we want to (are forced to) mount relay on the switch without actually having the _capability_ to relay messages, but this works well in this model as just another argument.

**Comment by jm-clius** [comment]
Ok, in 71b4bfb I try avoiding overloaded concepts like "light" and "full" node. I now rather refer to the _capability_ to relay messages or not. Lmk if this clears things up. cc @oskarth

**Review by oskarth — APPROVED** [review]
